source 'https://github.com/CocoaPods/Specs.git'

project 'SharedShoot.xcodeproj'
platform :ios, '8.0'
use_frameworks!

target 'SharedShoot' do
	pod 'AeroGearHttp', '0.8.0'
	pod 'AeroGearOAuth2', '0.8.0'
end
