source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'AeroGearSyncDemo.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearSyncClientJsonPatch', :git => 'https://github.com/aerogear/aerogear-ios-sync-client'

target 'AeroGearSyncDemoTests' do
	pod 'AeroGearSyncClientJsonPatch', :git => 'https://github.com/aerogear/aerogear-ios-sync-client'
end
