source 'https://github.com/CocoaPods/Specs.git'

project 'AeroGearSyncDemo.xcodeproj'
platform :ios, '9.0'
use_frameworks!

target 'AeroGearSyncDemo' do
	pod 'AeroGearSyncJsonPatch', :git => 'https://github.com/aerogear/aerogear-ios-sync', :branch => 'swift4'
	pod 'AeroGearSyncClientJsonPatch', :git => 'https://github.com/aerogear/aerogear-ios-sync-client', :branch => 'swift4'
	target 'AeroGearSyncDemoTests' do
		pod 'AeroGearSyncJsonPatch', :git => 'https://github.com/aerogear/aerogear-ios-sync', :branch => 'swift4'
		pod 'AeroGearSyncClientJsonPatch', :git => 'https://github.com/aerogear/aerogear-ios-sync-client', :branch => 'swift4'
	end
end
