xcodeproj 'AeroGear-OTP-Demo.xcodeproj'

platform :ios, '5.0'

pod 'AeroGear-OTP', :git => 'https://github.com/aerogear/aerogear-otp-ios.git', :branch  => 'wrongPath' 
pod 'AFNetworking', '1.0RC1'
pod 'SVProgressHUD', '0.8'
