source 'https://github.com/CocoaPods/Specs.git'
project 'helloworldpush.xcodeproj'
platform :ios, '9.0'
use_frameworks!

target 'helloworldpush' do
  pod 'AeroGear-Push-Swift', :git => 'https://github.com/aerogear/aerogear-ios-push', :branch => 'ios11'
end
