//  AGViewController.m
//
//  Generated by the the JBoss AeroGear Xcode Project Template on 6/17/13.
//  See Project's web site for more details http://www.aerogear.org
//

#import "AGMyLeadsViewController.h"
#import "AGLeadViewController.h"
#import "ProDoctorAPIClient.h"
#import "AGLead.h"
#import "LeadCell.h"

@implementation AGMyLeadsViewController {
    NSMutableArray *_leads;
    id<AGStore> _localStore;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor clearColor];
    
    _localStore = [[ProDoctorAPIClient sharedInstance] localStore];
    
    [[NSNotificationCenter defaultCenter]
     addObserver:self selector:@selector(myLeadRefresh) name:@"NewMyLeadNotification" object:nil];
    
    [self displayLeads];
}

- (void) displayLeads {
    _leads = [[_localStore readAll] mutableCopy];
}

- (void)viewDidUnload {
    [super viewDidUnload];
    // unregister our notification listener
    [[NSNotificationCenter defaultCenter]
     removeObserver:self name:@"NewMyLeadNotification" object:nil];
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [_leads count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *cellIdentifier = @"Cell";
    LeadCell *cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
    NSInteger row = [indexPath row];
    //AGLead *lead = [_leads objectAtIndex:row];
    AGLead *lead = [[AGLead alloc] initWithDictionary: [_leads objectAtIndex:row]];
    if (cell == nil) {
        cell = [[LeadCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellIdentifier withTableView:tableView andIndexPath:indexPath withImageDisplay:NO withIndicatorDisplay:NO];
    }

    [cell decorateCell:row inListCount:[_leads count] with:NO];
    
    cell.topLabel.text = [NSString stringWithFormat:@"%@.", lead.name];
    cell.bottomLabel.text = [NSString stringWithFormat:@"at: %@", lead.location];
    
    return cell;
}


- (void) myLeadRefresh {
    [self displayLeads];
    [self.tableView reloadData];
}


@end