//  AGViewController.h
//
//  Generated by the the JBoss AeroGear Xcode Project Template on 6/17/13.
//  See Project's web site for more details http://www.aerogear.org
//

#import <UIKit/UIKit.h>
#import "AGLeadViewController.h"

@interface AGMyLeadsViewController : UITableViewController
- (void) displayLeads;
- (void) saveLead:(AGLead *)lead;
@end