//  AGViewController.m
//
//  Generated by the the JBoss AeroGear Xcode Project Template on 6/17/13.
//  See Project's web site for more details http://www.aerogear.org
//

#import "AGViewController.h"
#import "ProDoctorAPIClient.h"

@implementation AGViewController {
    NSArray *_tasks;
}

- (void)viewDidLoad {
    [super viewDidLoad];

    self.title = @"Tasks";

    // access the singleton instance that holds our pipes
    ProDoctorAPIClient *apiClient = [ProDoctorAPIClient sharedInstance];

    // first, we need to login to the service

    // Note: here we use static strings but a login screen
    // will provide the necessary authentication details.
    [apiClient loginWithUsername:@"john" password:@"123" success:^{

        // logged in successfully

        // time to retrieve remote data
        [[apiClient tasksPipe] read:^(id responseObject) {
            // update our model
            _tasks = responseObject;

            // instruct table to refresh view
            [self.tableView reloadData];

        } failure:^(NSError *error) {
            NSLog(@"An error has occured during read! \n%@", error);
        }];

    } failure:^(NSError *error) {
        NSLog(@"An error has occured during login! \n%@", error);
    }];
}

- (void)viewDidUnload {
    [super viewDidUnload];
    // Release any retained subviews of the main view.
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [_tasks count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *CellIdentifier = @"Cell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
    
    if (cell == nil) {
        cell = [[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier];
    }
    
    NSUInteger row = [indexPath row];
    
    cell.textLabel.text = [[_tasks objectAtIndex:row] objectForKey:@"title"];
    
    return cell;
}

@end