xcodeproj 'AeroGear-Crypto-Demo.xcodeproj'
platform :ios, '5.0'
         
pod 'AeroGear', '1.4.0'
pod 'AeroGear-Crypto', '0.1.0'
pod 'UIActionSheet-Blocks', '1.0'
pod 'UIAlertView+Blocks', '0.7'
pod 'SVProgressHUD', '1.0'

