source 'https://github.com/CocoaPods/Specs.git'

project 'HelloWorldSwift.xcodeproj'
platform :ios, '9.0'
use_frameworks!

target 'HelloWorldSwift' do
    pod 'AeroGearPush-Swift', :path => '/Users/ziccardi/work/aerogear/aerogear-ios-push'
end
