source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Shoot.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearHttp', :git => "https://github.com/aerogear/aerogear-ios-http.git", :branch => "master"
pod 'AeroGearOAuth2', :git => "https://github.com/aerogear/aerogear-ios-oauth2.git", :branch => "master"
