source 'https://github.com/CocoaPods/Specs.git'

project 'Shoot.xcodeproj'
platform :ios, '8.0'
use_frameworks!

target 'Shoot' do
	pod 'AeroGearHttp', :git => 'http://github.com/aerogear/aerogear-ios-http'
	pod 'AeroGearOAuth2', :git => 'http://github.com/aerogear/aerogear-ios-oauth2'
end