source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Weather.xcodeproj'
platform :ios, '8.0'

pod 'AeroGearHttp', :git => "https://github.com/aerogear/aerogear-ios-http.git", :branch => "master"
