source 'https://github.com/CocoaPods/Specs.git'

project 'ChuckNorrisJokes.xcodeproj'
platform :ios, '8.0'
use_frameworks!

target 'ChuckNorrisJokes' do
	pod 'AeroGearHttp', :git => 'https://github.com/aerogear/aerogear-ios-http.git'
	pod 'AeroGearJsonSZ', :git => 'https://github.com/aerogear/aerogear-ios-jsonsz.git'
end