source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ChuckNorrisJokes.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearHttp', :git => "https://github.com/corinnekrych/aerogear-ios-http-1.git", :branch => "AGIOS-428.ios-8.3.migration"
pod 'AeroGearJsonSZ', :git => "https://github.com/corinnekrych/aerogear-ios-jsonsz.git", :branch => "AGIOS-428.ios-8.3.migration"
