source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ChuckNorrisJokes.xcodeproj'
platform :ios, '7.0'
use_frameworks!


pod 'AeroGearHttp', :git => 'https://github.com/aerogear/aerogear-ios-http.git'
pod 'AeroGearJsonSZ', :git => 'https://github.com/corinnekrych/aerogear-ios-jsonsz.git', :branch => 'AGIOS-457.ios7.min.deployement.target'
