source 'https://github.com/aerogear/Cocoapods-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'AeroGearSyncDemo.xcodeproj'
platform :ios, '8.0'

pod 'AeroGearSyncClient', :git => 'https://github.com/aerogear/aerogear-ios-sync-client.git', :branch => "master"
pod 'AeroGearSync/DiffMatchPatch', :git => "https://github.com/aerogear/aerogear-ios-sync.git", :branch => "master"

target 'AeroGearSyncDemoTests' do
    pod 'AeroGearSyncClient', :git => 'https://github.com/aerogear/aerogear-ios-sync-client.git', :branch => "master"
   pod 'AeroGearSync/DiffMatchPatch', :git => "https://github.com/aerogear/aerogear-ios-sync.git", :branch => "master" 
end
