source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'AeroGearSyncDemo.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearSyncClient', '1.0.0-alpha.1'
pod 'AeroGearSync/DiffMatchPatch', '1.0.0-alpha.1'

target 'AeroGearSyncDemoTests' do
    pod 'AeroGearSyncClient', '1.0.0-alpha.1'
    pod 'AeroGearSync/DiffMatchPatch', '1.0.0-alpha.1'
end
