source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'AeroGearSyncDemo.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearSyncClient', :git => 'https://github.com/cvasilak/aerogear-ios-sync-client.git', :branch => "custom.repo"
pod 'AeroGearSync/DiffMatchPatch', :git => "https://github.com/cvasilak/aerogear-ios-sync.git", :branch => "custom.repo"

target 'AeroGearSyncDemoTests' do
    pod 'AeroGearSyncClient', :git => 'https://github.com/cvasilak/aerogear-ios-sync-client.git', :branch => "custom.repo"
    pod 'AeroGearSync/DiffMatchPatch', :git => "https://github.com/cvasilak/aerogear-ios-sync.git", :branch => "custom.repo"
end
