xcodeproj 'AeroDoc.xcodeproj'
platform :ios, '5.0'
         
pod 'AeroGear', :git => 'https://github.com/aerogear/aerogear-ios.git'
pod 'AeroGearPush', :git => 'https://github.com/aerogear/aerogear-push-ios-registration.git'
