//  ProDoctorAPIClient.h
//
//  Generated by the the JBoss AeroGear Xcode Project Template on 6/17/13.
//  See Project's web site for more details http://www.aerogear.org
//

#import "AeroGear.h"

@class AGLead;

@interface ProDoctorAPIClient : NSObject

@property(readonly, nonatomic) id<AGPipe> leadsPipe;
@property(readonly, nonatomic) id<AGPipe> agentPipe;

@property(readonly, nonatomic) id<AGStore> localStore;
@property(readonly, nonatomic) id<AGStore> pushedLocalStore;

@property(readonly, nonatomic) NSNumber *userId;
@property(readonly, nonatomic) NSString *loginName;
@property(readonly, nonatomic) NSString *location;
@property(readonly, nonatomic) NSString *status;

+ (ProDoctorAPIClient *)sharedInstance;

- (void)loginWithUsername:(NSString *)username
                 password:(NSString *)password
                  success:(void (^)())success
                  failure:(void (^)(NSError *error))failure;

- (void)fetchLeads:(void (^)(NSMutableArray *leads))success
           failure:(void (^)(NSError *error))failure;

- (void)postLead:(AGLead *)lead
         success:(void (^)())success
         failure:(void (^)(NSError *error))failure;

- (void)changeStatus:(NSString*) status
             success:(void (^)())success
             failure:(void (^)(NSError *error))failure;
@end
