source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Authentication.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearHttp', :git => "https://github.com/aerogear/aerogear-ios-http.git", :branch => "master"
