source 'https://github.com/CocoaPods/Specs.git'

project 'Authentication.xcodeproj'
platform :ios, '8.0'
use_frameworks!

target 'Authentication' do
	pod 'AeroGearHttp', :git => 'https://github.com/aerogear/aerogear-ios-http.git'
end